spring.application.name=backend

# Server configuration
server.port=8084

# Database configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/backend_db
spring.datasource.username=${SPRING_FLYWAY_USER}
spring.datasource.password=${SPRING_FLYWAY_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://postgres:5432/backend_db
spring.flyway.user=${SPRING_FLYWAY_USER}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD}
spring.flyway.placeholders.db_owner=${SPRING_FLYWAY_USER}
