spring.application.name=backend
# Server configuration
server.port=8084
# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Flyway configuration
spring.flyway.enabled=true
spring.flyway.url=${SPRING_FLYWAY_URL}
spring.flyway.user=${SPRING_FLYWAY_USER}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD}
# Backend service additional props
back-options.filesPath=${BACK-OPTIONS_FILEPATH}
back-options.allowedOrigin=${BACK-OPTIONS_ALLOWEDORIGIN}
back-options.jwtSecretKey=${BACK-OPTIONS_JWTSECRETKEY}
back-options.jwtExpiration=${BACK-OPTIONS_JWTEXPIRATION}

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
